#! /bin/bash

ORIENTS="1.7.8 2.0.7 2.1.4"
GROOVYS="2.4.5"
MODELS="light heavy"

rm -f performance.log

for groovy in $GROOVYS ; do
	for orient in $ORIENTS ; do
		for model in $MODELS ; do
			./gradlew -q clean run -PGV=${groovy} -POV=${orient} -Pmodel=${model}
		done
	done
done
